name: skript-worlds
version: '${project.version}'
main: me.github.reportcardsmc.skriptworlds.SkriptWorlds
api-version: 1.17
depend: [ 'Skript', 'Multiverse-Core' ]
authors: [ ReportCards ]
description: A Skript Addon to hook into multiverse
